### ISSUE TITLE
port dataset from lexibank-old

### ISSUE THREAD

**Issue by LinguList** [lexibank/wichmannmixezoquean#1]
this should be straightforward, as we have all data there, even compiled cldf, and segments.

**Comment by LinguList** [comment]
first pass is done, we need to only adjust the python script.

**Comment by chrzyki** [comment]
Should I take care of that? Already went through something similar with leejaponic and leeainu.

**Comment by SimonGreenhill** [comment]
already done! https://github.com/lexibank/wichmannmixezoquean
